### ISSUE TITLE
Modal covers status bar but leaves gap at bottom on some devices

### ISSUE THREAD

**Issue by lijianyu1985** [23mf/react-native-translucent-modal#1]
Modal covers status bar but leaves gap at bottom on some devices

**Comment by lijianyu1985** [comment]
modal下面有个空白区，高度和statusbar同样高

**Comment by pinguo-zhouwei** [comment]
@lijianyu1985 Can you tell me the specific model number?

**Comment by rpascal-castro** [comment]
**Invariant Violation: Invariant Violation: requireNativeComponent: "RCTTranslucentModalHostView" was not found in the UIManager.**

Expo 34
Android


![Error](https://user-images.githubusercontent.com/58040829/69351742-28d32800-0c52-11ea-97a9-0ce15316deff.png)

**Comment by pinguo-zhouwei** [comment]
hi, see that you have no feedback, I will close the issue first, if there are still problems, please provide the code and more information
