### ISSUE TITLE
文档有错误

### ISSUE THREAD

**Issue by YuanKJ-** [23mf/react-native-translucent-modal#5]
库是好用的，然而文档说明不全面，在安卓上还需要引入本地的module，这部分在文档上面找不到，跟着Example导入的module最后才运行成功，希望可以补充一下

**Comment by congshengwu** [comment]
> 库是好用的，然而文档说明不全面，在安卓上还需要引入本地的module，这部分在文档上面找不到，跟着Example导入的module最后才运行成功，希望可以补充一下

你好，我这面npm install加react native link后直接可以用了，请问你那面还需要引入什么本地模块？

**Comment by pinguo-zhouwei** [comment]
@YuanKJ-  link 就是干这事儿的
